### ISSUE TITLE
How to get a runnable binary?

### ISSUE THREAD

**Issue by zhblue** [DragonRocket/MiniSuperMarioDemo-Assembly8088#1]
Would you please upload a release file ?

**Comment by DragonRocket** [comment]
Sure! You can now download the runnable binary from the [Mini Super Mario Demo Assembly 8088 v1.0](https://github.com/DragonRocket/MiniSuperMarioDemo-Assembly8088/releases/tag/pre-release) page.

I have also added Build and Run Instructions in the Readme.md file.

Thank You!
